import Head from 'next/head'
import { Inter } from 'next/font/google'
import { signIn } from "next-auth/react"


const inter = Inter({ subsets: ['latin'] })




export default function Home() {

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <button onClick={() => {
          signIn()
        }}>
          Login In
        </button>

        <button>
          Log out
        </button>
      </main>
    </div>
  )
}
